# -------- BUILD STAGE --------
    FROM node:22-alpine AS builder

    WORKDIR /app
    
    COPY package*.json ./
    RUN npm ci
    
    COPY . .
    
    ARG VITE_API_URL
    ENV VITE_API_URL=${VITE_API_URL}
    
    RUN npm run build
    
    
    # -------- PRODUCTION STAGE --------
    FROM nginx:1.27-alpine3.22
    
    # Remove default config if needed
    # RUN rm /etc/nginx/conf.d/default.conf
    
    # Fix permissions for non-root execution
    RUN chown -R nginx:nginx /usr/share/nginx/html \
        && chown -R nginx:nginx /var/cache/nginx \
        && chown -R nginx:nginx /var/log/nginx \
        && chown -R nginx:nginx /etc/nginx/conf.d
    
    COPY --from=builder /app/dist /usr/share/nginx/html
    COPY nginx.conf /etc/nginx/conf.d/default.conf
    
    # 🔥 IMPORTANT: use non-privileged port
    EXPOSE 8080
    
    # Switch to non-root user
    USER nginx
    
    CMD ["nginx", "-g", "daemon off;"]